theme: jekyll-theme-minimal

title: UnderZ
description: UnderZ JS Library.
show_downloads: true
google_analytics:
owner_name: hlaCk
collab: BlackEagleSA
repository_url: https://github.com/hlaCk/UnderZ

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

gems:
  - jekyll-archives
